In [3]:
import numpy as np

In [4]:
print(np.__version__)

1.21.2


In [5]:
my_list = [-17, 0, 4, 5, 9]
my_array_from_list = np.array(my_list)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [6]:
my_array_from_list * 10

array([-170,    0,   40,   50,   90])

In [8]:
my_tuple = (14, -3, 54, 5+7j)
np.array(my_tuple)

array([14.+0.j, -3.+0.j, 54.+0.j,  5.+7.j])

### difference between python and numpy data structures

In [9]:
my_tuple * 6

(14,
 -3,
 54,
 (5+7j),
 14,
 -3,
 54,
 (5+7j),
 14,
 -3,
 54,
 (5+7j),
 14,
 -3,
 54,
 (5+7j),
 14,
 -3,
 54,
 (5+7j),
 14,
 -3,
 54,
 (5+7j))

In [10]:
np.array(my_tuple) * 6

array([ 84. +0.j, -18. +0.j, 324. +0.j,  30.+42.j])