# array shape manipulation

In [6]:
import numpy as np

### reshape

In [7]:
my_start_array = np.array(np.arange(24))
my_start_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [8]:
my_start_array.shape

(24,)

In [9]:
my_3_8_array = my_start_array.reshape((3, 8))
my_3_8_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [11]:
my_3_8_array[0, 0] = 123
my_start_array

array([123,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [13]:
my_ravel_array = my_3_8_array.ravel()
my_ravel_array

array([123,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [14]:
my_ravel_array.shape

(24,)

In [15]:
for n in my_3_8_array.flat:
    print(n)

123
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
