In [1]:
import numpy as np

In [4]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [5]:
my_3d_array.shape

(2, 7, 5)

In [6]:
my_3d_array.ndim

3

In [7]:
my_3d_array.size

70

In [8]:
my_3d_array.dtype

dtype('int64')

In [10]:
5 * my_3d_array - 2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [11]:
left_mat = np.arange(6).reshape(2, 3)
right_mat = np.arange(15).reshape(3, 5)

In [12]:
np.inner(left_mat, right_mat)

ValueError: shapes (2,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [13]:
np.dot(left_mat, right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

operating along axes

In [14]:
my_3d_array.sum()

2415

In [15]:
(69*70)/2

2415.0

In [16]:
my_3d_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [17]:
my_3d_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [18]:
my_3d_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

broadcasting rules

In [20]:
my_2d_array = np.ones(35, dtype='int_').reshape(7, 5) * 3
my_2d_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [22]:
my_random_2d_array = np.random.random((7, 5))
my_3d_array * my_random_2d_array

array([[[ 0.        ,  0.2210144 ,  0.1691424 ,  0.86333343,
          1.8627701 ],
        [ 3.1062983 ,  3.66578145,  5.51370698,  6.93709695,
          6.39396718],
        [ 4.94197371,  3.27574696, 10.06350517, 10.33441366,
         13.21387125],
        [10.28747384,  9.57443369,  1.55022185, 17.76062641,
         11.48189661],
        [12.17127595, 16.85873967,  7.40119669,  0.18131673,
          5.78786896],
        [ 3.62740922,  1.78133232,  0.26909258,  2.99971074,
         23.86727363],
        [ 0.42054547, 11.43961478,  2.6301355 , 16.12430037,
         12.73960004]],

       [[24.84631367,  7.95651841,  3.12913447, 10.93555679,
         18.16200849],
        [24.85038637, 25.04950656, 33.08224189, 37.28689611,
         31.2593951 ],
        [22.23888172, 13.6985782 , 39.41539526, 38.15783507,
         46.24854938],
        [34.29157947, 30.51850738,  4.74185506, 52.29517776,
         32.63275878],
        [33.47100886, 44.95663912, 19.1758278 ,  0.45723348,
         14.2

In [23]:
np.set_printoptions(precision=4)
my_3d_array * my_random_2d_array

array([[[ 0.    ,  0.221 ,  0.1691,  0.8633,  1.8628],
        [ 3.1063,  3.6658,  5.5137,  6.9371,  6.394 ],
        [ 4.942 ,  3.2757, 10.0635, 10.3344, 13.2139],
        [10.2875,  9.5744,  1.5502, 17.7606, 11.4819],
        [12.1713, 16.8587,  7.4012,  0.1813,  5.7879],
        [ 3.6274,  1.7813,  0.2691,  2.9997, 23.8673],
        [ 0.4205, 11.4396,  2.6301, 16.1243, 12.7396]],

       [[24.8463,  7.9565,  3.1291, 10.9356, 18.162 ],
        [24.8504, 25.0495, 33.0822, 37.2869, 31.2594],
        [22.2389, 13.6986, 39.4154, 38.1578, 46.2485],
        [34.2916, 30.5185,  4.7419, 52.2952, 32.6328],
        [33.471 , 44.9566, 19.1758,  0.4572, 14.2285],
        [ 8.7058,  4.1793,  0.6179,  6.7493, 52.6726],
        [ 0.9112, 24.3553,  5.5068, 33.2258, 25.8539]]])

In [24]:
my_vector = np.arange(5) * 7
my_vector[0] = -1
my_vector

array([-1,  7, 14, 21, 28])

In [25]:
my_3d_array/my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])

In [26]:
my_3d_array%my_vector

array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  4, 12, 13, 14],
        [ 0,  2,  3, 18, 19],
        [ 0,  0,  8,  2, 24],
        [ 0,  5, 13,  7,  1],
        [ 0,  3,  4, 12,  6]],

       [[ 0,  1,  9, 17, 11],
        [ 0,  6,  0,  1, 16],
        [ 0,  4,  5,  6, 21],
        [ 0,  2, 10, 11, 26],
        [ 0,  0,  1, 16,  3],
        [ 0,  5,  6,  0,  8],
        [ 0,  3, 11,  5, 13]]])