In [2]:
import numpy as np

In [3]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a

array([[1, 1],
       [2, 2],
       [3, 3]])

In [4]:
b = a.flatten()
b

array([1, 1, 2, 2, 3, 3])

In [6]:
np.insert(b, [2, 2], [5, 6])

array([1, 1, 5, 6, 2, 2, 3, 3])

In [7]:
np.insert(b, slice(2, 4), [5, 6])

array([1, 1, 5, 2, 6, 2, 3, 3])

In [8]:
np.insert(b, [2, 2], [7.13, False])

array([1, 1, 7, 0, 2, 2, 3, 3])

In [9]:
x = np.arange(8).reshape(2, 4)
idx = (1, 3)
np.insert(x, idx, 999, axis=1)

array([[  0, 999,   1,   2, 999,   3],
       [  4, 999,   5,   6, 999,   7]])