In [1]:
import numpy as np

In [2]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [3]:
np.arange(10, 23)-10+1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [4]:
len(np.arange(10, 23))

13

In [5]:
my_range_array = np.arange(10, 23)
my_range_array.size

13

In [6]:
np.arange(10, 23).size

13

In [7]:
np.arange(10, 23, 5).size


3

In [8]:
np.arange(26, step=6)

array([ 0,  6, 12, 18, 24])