# joining and splitting arrays

In [1]:
import numpy as np

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6]])

In [5]:
together = np.concatenate((a, b), axis=0)

In [6]:
together

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
together.shape

(3, 2)

In [8]:
together[1, 1] = 555

In [9]:
together

array([[  1,   2],
       [  3, 555],
       [  5,   6]])

In [10]:
a

array([[1, 2],
       [3, 4]])

In [12]:
c = np.array([[1, 2], [3 ,4]]) *3 +5
c

array([[ 8, 11],
       [14, 17]])

In [13]:
np.concatenate((a, c), axis=1)

array([[ 1,  2,  8, 11],
       [ 3,  4, 14, 17]])

In [14]:
arrays = np.zeros((5, 3, 4))
for n in range(5):
    arrays[n] = np.random.randn(3, 4)

arrays

array([[[ 1.12700650e+00, -1.43698142e-03,  1.86740001e-01,
          1.42760769e-03],
        [ 1.47708116e+00,  1.30820608e+00, -1.55100360e+00,
         -2.74896857e-01],
        [-2.19223532e+00,  9.25647866e-01, -1.90293176e+00,
         -4.04622888e-01]],

       [[-4.23581466e-02,  1.16845502e+00, -1.17888515e+00,
         -3.63181702e-01],
        [-9.82418688e-01,  3.42446153e-01,  3.05672356e-01,
          1.54271949e-01],
        [ 6.14982967e-02,  7.45459312e-01, -2.46124822e+00,
         -4.43567724e-01]],

       [[ 2.52184768e-01,  6.60651196e-01,  5.68112997e-01,
         -5.63676980e-01],
        [-1.07402099e+00,  3.07918030e-01,  1.31887789e+00,
          1.82444596e+00],
        [-2.64852194e-01, -1.10946434e+00,  9.94366283e-02,
          7.57028650e-01]],

       [[-6.61909152e-01,  1.11889623e-01, -1.27370761e+00,
          3.92133843e-01],
        [ 7.23608936e-01, -8.30169559e-01,  9.32044474e-01,
          4.98297024e-01],
        [-1.36817957e+00, -5.30357014

In [15]:
stack0 = np.stack(arrays, axis=0)
stack1 = np.stack(arrays, axis=1)
stack2 = np.stack(arrays, axis=2)

In [16]:
stack0

array([[[ 1.12700650e+00, -1.43698142e-03,  1.86740001e-01,
          1.42760769e-03],
        [ 1.47708116e+00,  1.30820608e+00, -1.55100360e+00,
         -2.74896857e-01],
        [-2.19223532e+00,  9.25647866e-01, -1.90293176e+00,
         -4.04622888e-01]],

       [[-4.23581466e-02,  1.16845502e+00, -1.17888515e+00,
         -3.63181702e-01],
        [-9.82418688e-01,  3.42446153e-01,  3.05672356e-01,
          1.54271949e-01],
        [ 6.14982967e-02,  7.45459312e-01, -2.46124822e+00,
         -4.43567724e-01]],

       [[ 2.52184768e-01,  6.60651196e-01,  5.68112997e-01,
         -5.63676980e-01],
        [-1.07402099e+00,  3.07918030e-01,  1.31887789e+00,
          1.82444596e+00],
        [-2.64852194e-01, -1.10946434e+00,  9.94366283e-02,
          7.57028650e-01]],

       [[-6.61909152e-01,  1.11889623e-01, -1.27370761e+00,
          3.92133843e-01],
        [ 7.23608936e-01, -8.30169559e-01,  9.32044474e-01,
          4.98297024e-01],
        [-1.36817957e+00, -5.30357014

In [17]:
stack1

array([[[ 1.12700650e+00, -1.43698142e-03,  1.86740001e-01,
          1.42760769e-03],
        [-4.23581466e-02,  1.16845502e+00, -1.17888515e+00,
         -3.63181702e-01],
        [ 2.52184768e-01,  6.60651196e-01,  5.68112997e-01,
         -5.63676980e-01],
        [-6.61909152e-01,  1.11889623e-01, -1.27370761e+00,
          3.92133843e-01],
        [ 2.01906891e+00, -1.80150627e+00,  1.43204592e+00,
          3.16373730e-01]],

       [[ 1.47708116e+00,  1.30820608e+00, -1.55100360e+00,
         -2.74896857e-01],
        [-9.82418688e-01,  3.42446153e-01,  3.05672356e-01,
          1.54271949e-01],
        [-1.07402099e+00,  3.07918030e-01,  1.31887789e+00,
          1.82444596e+00],
        [ 7.23608936e-01, -8.30169559e-01,  9.32044474e-01,
          4.98297024e-01],
        [-1.04895306e+00,  6.99295345e-01, -8.23176495e-01,
         -1.41371025e+00]],

       [[-2.19223532e+00,  9.25647866e-01, -1.90293176e+00,
         -4.04622888e-01],
        [ 6.14982967e-02,  7.45459312e-

In [18]:
stack2

array([[[ 1.12700650e+00, -4.23581466e-02,  2.52184768e-01,
         -6.61909152e-01,  2.01906891e+00],
        [-1.43698142e-03,  1.16845502e+00,  6.60651196e-01,
          1.11889623e-01, -1.80150627e+00],
        [ 1.86740001e-01, -1.17888515e+00,  5.68112997e-01,
         -1.27370761e+00,  1.43204592e+00],
        [ 1.42760769e-03, -3.63181702e-01, -5.63676980e-01,
          3.92133843e-01,  3.16373730e-01]],

       [[ 1.47708116e+00, -9.82418688e-01, -1.07402099e+00,
          7.23608936e-01, -1.04895306e+00],
        [ 1.30820608e+00,  3.42446153e-01,  3.07918030e-01,
         -8.30169559e-01,  6.99295345e-01],
        [-1.55100360e+00,  3.05672356e-01,  1.31887789e+00,
          9.32044474e-01, -8.23176495e-01],
        [-2.74896857e-01,  1.54271949e-01,  1.82444596e+00,
          4.98297024e-01, -1.41371025e+00]],

       [[-2.19223532e+00,  6.14982967e-02, -2.64852194e-01,
         -1.36817957e+00, -3.29968973e-01],
        [ 9.25647866e-01,  7.45459312e-01, -1.10946434e+00,


In [20]:
print(arrays.shape, stack0.shape, stack1.shape, stack2.shape)

(5, 3, 4) (5, 3, 4) (3, 5, 4) (3, 4, 5)


In [23]:
temp = np.arange(5)
temp

array([0, 1, 2, 3, 4])

In [26]:
np.split(temp, 1)

[array([0, 1, 2, 3, 4])]

In [27]:
before_split = stack0
before_split.shape

(5, 3, 4)

In [32]:
s0 = np.split(before_split, 5, axis=0)
s0

[array([[[ 1.12700650e+00, -1.43698142e-03,  1.86740001e-01,
           1.42760769e-03],
         [ 1.47708116e+00,  1.30820608e+00, -1.55100360e+00,
          -2.74896857e-01],
         [-2.19223532e+00,  9.25647866e-01, -1.90293176e+00,
          -4.04622888e-01]]]),
 array([[[-0.04235815,  1.16845502, -1.17888515, -0.3631817 ],
         [-0.98241869,  0.34244615,  0.30567236,  0.15427195],
         [ 0.0614983 ,  0.74545931, -2.46124822, -0.44356772]]]),
 array([[[ 0.25218477,  0.6606512 ,  0.568113  , -0.56367698],
         [-1.07402099,  0.30791803,  1.31887789,  1.82444596],
         [-0.26485219, -1.10946434,  0.09943663,  0.75702865]]]),
 array([[[-0.66190915,  0.11188962, -1.27370761,  0.39213384],
         [ 0.72360894, -0.83016956,  0.93204447,  0.49829702],
         [-1.36817957, -0.53035701, -1.55552218, -0.21092539]]]),
 array([[[ 2.01906891, -1.80150627,  1.43204592,  0.31637373],
         [-1.04895306,  0.69929534, -0.8231765 , -1.41371025],
         [-0.32996897,  0.93

In [33]:
type(s0)

list

In [34]:
s0[1]

array([[[-0.04235815,  1.16845502, -1.17888515, -0.3631817 ],
        [-0.98241869,  0.34244615,  0.30567236,  0.15427195],
        [ 0.0614983 ,  0.74545931, -2.46124822, -0.44356772]]])

In [36]:
s0[1].shape

(1, 3, 4)

In [37]:
s1 = np.split(before_split, 3, axis=1)
s1

[array([[[ 1.12700650e+00, -1.43698142e-03,  1.86740001e-01,
           1.42760769e-03]],
 
        [[-4.23581466e-02,  1.16845502e+00, -1.17888515e+00,
          -3.63181702e-01]],
 
        [[ 2.52184768e-01,  6.60651196e-01,  5.68112997e-01,
          -5.63676980e-01]],
 
        [[-6.61909152e-01,  1.11889623e-01, -1.27370761e+00,
           3.92133843e-01]],
 
        [[ 2.01906891e+00, -1.80150627e+00,  1.43204592e+00,
           3.16373730e-01]]]),
 array([[[ 1.47708116,  1.30820608, -1.5510036 , -0.27489686]],
 
        [[-0.98241869,  0.34244615,  0.30567236,  0.15427195]],
 
        [[-1.07402099,  0.30791803,  1.31887789,  1.82444596]],
 
        [[ 0.72360894, -0.83016956,  0.93204447,  0.49829702]],
 
        [[-1.04895306,  0.69929534, -0.8231765 , -1.41371025]]]),
 array([[[-2.19223532,  0.92564787, -1.90293176, -0.40462289]],
 
        [[ 0.0614983 ,  0.74545931, -2.46124822, -0.44356772]],
 
        [[-0.26485219, -1.10946434,  0.09943663,  0.75702865]],
 
        [[-1

In [43]:
s2 = np.split(before_split, 4, axis=2)
s2

[array([[[ 1.1270065 ],
         [ 1.47708116],
         [-2.19223532]],
 
        [[-0.04235815],
         [-0.98241869],
         [ 0.0614983 ]],
 
        [[ 0.25218477],
         [-1.07402099],
         [-0.26485219]],
 
        [[-0.66190915],
         [ 0.72360894],
         [-1.36817957]],
 
        [[ 2.01906891],
         [-1.04895306],
         [-0.32996897]]]),
 array([[[-1.43698142e-03],
         [ 1.30820608e+00],
         [ 9.25647866e-01]],
 
        [[ 1.16845502e+00],
         [ 3.42446153e-01],
         [ 7.45459312e-01]],
 
        [[ 6.60651196e-01],
         [ 3.07918030e-01],
         [-1.10946434e+00]],
 
        [[ 1.11889623e-01],
         [-8.30169559e-01],
         [-5.30357014e-01]],
 
        [[-1.80150627e+00],
         [ 6.99295345e-01],
         [ 9.31834315e-01]]]),
 array([[[ 0.18674   ],
         [-1.5510036 ],
         [-1.90293176]],
 
        [[-1.17888515],
         [ 0.30567236],
         [-2.46124822]],
 
        [[ 0.568113  ],
         [ 1.318