In [2]:
import numpy as np

In [4]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [5]:
my_vector[0]

-17

In [6]:
my_vector[0] = -102
my_vector

array([-102,   -4,    0,    2,   21,   37,  105])

In [9]:
my_vector[-3]

21

In [10]:
my_vector[305 % 7]

21

In [11]:
my_vector.size

7

two dimensional arrays

In [20]:
my_array = np.arange(35)
my_array.shape = (7, 5)
my_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [15]:
my_array[2]

array([10, 11, 12, 13, 14])

In [21]:
my_array[-2]

array([25, 26, 27, 28, 29])

In [22]:
my_array[5, 2]

27

In [23]:
row = 5
column = 2
my_array[row, column]

27


three dimensional array

In [24]:
my_3d_array = np.arange(70)
my_3d_array.shape = (2, 7, 5)
my_3d_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [25]:
my_3d_array[1]

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [26]:
my_3d_array[1, 3]

array([50, 51, 52, 53, 54])

In [27]:
my_3d_array[1, 1, 3]

43