# views and copies

In [ ]:
import numpy as np

In [2]:
mi_casa = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [3]:
su_casa = mi_casa

### same or different

In [4]:
mi_casa is su_casa

True

In [5]:
id(mi_casa)

140306422627568

In [6]:
id(su_casa)

140306422627568

In [7]:
mi_casa == su_casa

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [9]:
su_casa[4] = 1010
su_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [12]:
mi_casa

array([ -45,  -31,  -12,    0, 1010,   25,   51,   99])

In [15]:
tree_house = np.array([-45, -31, -12, 0, 2, 25, 51, 99])

In [16]:
tree_house == su_casa

array([ True,  True,  True,  True, False,  True,  True,  True])

In [18]:
print(id(tree_house))
print(id(mi_casa))

140306420075568
140306422627568


In [19]:
tree_house[0] = 214

In [20]:
tree_house == mi_casa

array([False,  True,  True,  True, False,  True,  True,  True])

In [21]:
tree_house is mi_casa

False

## view: a shallow copy

In [22]:
farm_house = tree_house.view()
farm_house.shape = (2, 4)

In [23]:
tree_house

array([214, -31, -12,   0,   2,  25,  51,  99])

In [24]:
farm_house

array([[214, -31, -12,   0],
       [  2,  25,  51,  99]])

In [25]:
tree_house[3] = -111
farm_house

array([[ 214,  -31,  -12, -111],
       [   2,   25,   51,   99]])

In [26]:
dog_house = np.copy(tree_house)
dog_house[0] = -121
dog_house

array([-121,  -31,  -12, -111,    2,   25,   51,   99])

In [27]:
tree_house

array([ 214,  -31,  -12, -111,    2,   25,   51,   99])